auth_server:
  # Public dummy UAA for local development usage only!
  # Username/password: credhub/password
  trust_store: src/test/resources/auth_server_trust_store.jks
  trust_store_password: changeit

encryption:
  keys:
  - encryption_password: opensesame
    provider_type: internal
    active: true
  - encryption_password: correcthorsebatterystaple
    provider_type: internal
  key_creation_enabled: true
  
security:
  authorization:
    acls:
      # Change to true to enable ACL enforcement
      enabled: false

logging:
  config: src/main/resources/log4j2.properties

server:
  port: ${SKIL_CREDHUB_PORT:9000}
  ssl:
    enabled: true
    key_store: src/test/resources/key_store.jks
    key_password: changeit
    key_alias: cert
    ciphers: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    client_auth: want
    trust_store: src/test/resources/trust_store.jks
    trust_store_password: changeit
    trust_store_type: JKS
    enabled-protocols: TLSv1.2

spring:
  profiles:
    include: dev-remote-uaa
